version: "3.7"

services:
  database:
    container_name: database
    image: postgres:13.3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 20s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=BookService
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgresBookService:/var/lib/postgresql/data


volumes:
  postgres:
    name: postgresBookService