spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/BookService}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_FILE_SIZE:100MB}
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  main:
    allow-bean-definition-overriding: true

jwt:
  subject: user
  issuer: course
  secret: J7gzxsdfdsdsfsklill234czxcQgfJ7gQgfczxc
  tokenExpiresIn: 432000

urls:
  me: ${BACKEND_URL:http://localhost:8080}
  frontend: ${CLIENT_URL:http://localhost:4200}
  confirm-token-url: ${CONFIRM_TOKEN_URL:http://localhost:4200/auth/confirm}

files:
  storage-directory: ${STORAGE_DIRECTORY:./images}

file:
  images:
    compression-quality: ${COMPRESSION_QUALITY:0.2}

mail:
  host: smtp.mail.ru
  port: 465
  username: "vl7shabyandex.ru@mail.ru"
  password: KdeWxX43ytJsmttdpVua
  protocol: smtps
  smtps:
    auth: true

confirm-token:
  expired-after: ${EXPIRED_TIME:30}

server:
  port: ${SERVER_PORT:8080}