spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/BookService}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  main:
    allow-bean-definition-overriding: true

jwt:
  subject: user
  issuer: course
  secret: J7gzxsdfdsdsfsklill234czxcQgfJ7gQgfczxc
  tokenExpiresIn: 432000

urls:
  me: ${BACKEND_URL:http://localhost:8080}
  frontend: ${CLIENT_URL:http://localhost:4200}

files:
  storage-directory: ${STORAGE_DIRECTORY:./images}

file:
  images:
    compression-quality: 0.2